### ISSUE TITLE
IEEE Xplore changed?

### ISSUE THREAD

**Issue by aluex** [alinush/ck#2] opened 2020-08-08 14:36 UTC
Sample URL: https://ieeexplore.ieee.org/document/8765347

To reproduce:

run `ck a https://ieeexplore.ieee.org/document/8765347`

and get

`    pdfurl = elem['src']
TypeError: 'NoneType' object is not subscriptable`

**Comment by alinush** [comment] 2020-09-07 17:30
I am not sure how to reproduce this, because the PDF is paywalled and I can't get access to it...

**Comment by alinush** [comment] 2020-09-07 23:13
Okay, this is fixed in d7f830c0035b50543a5a882019addc4de47a895d.
The problem was ieexeplore accepts two types of links:

 - [https://ieeexplore.ieee.org/document/7958589](https://ieeexplore.ieee.org/document/7958589)
 - [https://ieeexplore.ieee.org/abstract/document/7958589](https://ieeexplore.ieee.org/abstract/document/7958589)

...and our parsing was not general enough for both.

**Closed as completed by alinush** 2020-09-07 23:13 UTC
